# Ejecutar borrando volumen previo: 
## (docker volume rm vol-mysql-root-dev || true) && docker volume create vol-mysql-root-dev && docker-compose -f docker-compose-mysql-root.yml up -d
# Detener: 
## docker-compose -f docker-compose-mysql-root.yml down
# crear network
## docker network create vol-mysql-net
name: ${PROJECT_NAME}
services:
  notifier-api:
    image: "${IMAGE_TAG}"
    container_name: ${PROJECT_NAME}-notifier-api
    restart: always
    networks:
      - notifier-network
    ports:
      - "${API_PORT}:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "${ASPNETCORE_ENVIRONMENT}"      

networks:
  notifier-network: